Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:845677511246:task-definition/first-run-task-definition:2" # Specify the ARN of your task definition (arn:aws:ecs:region:account-id:task-definition/task-definition-family-name:task-definition-revision-number)
        LoadBalancerInfo: 
          ContainerName: "sample-app" # Specify the name of your Amazon ECS application's container
          ContainerPort: "80" # Specify the port for your container where traffic reroutes 
