version: 0.0
# In the Resources section specify the name, alias, 
# target version, and (optional) the current version of your AWS Lambda function. 
Resources:
  - PythonLambda: # Replace "MyFunction" with the name of your Lambda function 
      Type: AWS::Lambda::Function
      Properties:
        Name: "python-lambda" # Specify the name of your Lambda function
        Alias: "staging" # Specify the alias for your Lambda function
        CurrentVersion: "1" # Specify the current version of your Lambda function
        TargetVersion: "2" # Specify the version of your Lambda function to deploy
